Fichier Installation Fonctionnel. Fichier De désinstallation à prévoir. Fichier Pedt à jour. Fichier pedtlauncher à finir.

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -1,22 +1,97 @@
-DIR=~/.automatic_courses_player
-if [ -d "$DIR" ];then
-    echo ".automatic_courses_player directory exists."
+ExistPack1=0
+existPack1=0
+
+
+# CHECKING PACKAGES EXISTENCE -----------------------------------
+
+Pack1="xclip"
+
+pack1="khal"
+
+
+apt-cache pkgnames | grep -q $Pack1
+
+if [ $? -eq 0 ]; then
+    echo "$Pack1  is installed!"
 else
-    mkdir ~/.automatic_courses_player
-    echo ".automatic_courses_player directory do not exist, and was created."
+    echo "Package $Pack1 is NOT installed!"
+    ExistPack1=1
 fi
 
-cp -r * ~/.automatic_courses_player
-cd ~/.automatic_courses_player
 
-DIR=~/bin
-if [ -d "$DIR" ];then
-    echo "Bin directory exists."
+apt-cache pkgnames | grep -q $pack1
+
+if [ $? -eq 0 ]; then
+    echo "$pack1  is installed!"
 else
-    mkdir ~/bin
-    echo "Bin directory do not exist, and was created."
+    echo "Package  $pack1 is NOT installed!"
+    existPack1=1
 fi
 
-mv ./pedt ~/bin
-cd ~/bin
+
+# END OF CHECKING PACKAGES EXISTENCE -----------------------------------
+
+echo # DISPLAYING INSTALLATIONS REQUESTS TO PURSUE --------------------------
+
+# NOT mandatory packages ++++++++++
+
+if [ $((existPack1)) -ne 0 ]; then
+      printf "To benefit from all the package options install the following packages :\n\n"
+
+      if [ $existPack1 -ne 0 ]; then
+          echo "- $pack1  (this package is NOT mandatory, but recomended if you wish to consult your courses agenda)"
+          echo "- Try the following commands : apt-get install $pack1\n"
+      fi
+fi
+
+
+# MANDATORY packages +++++++++++++
+
+
+if [ $((ExistPack1)) -ne 0 ]; then
+
+      printf "To pursue installation, please install the following packages :\n\n"
+      if [ $ExistPack1 -ne 0 ]; then
+          echo "- $Pack1"
+          echo "- the following command : apt-get install $Pack1"
+      fi
+
+      exit 0
+fi
+
+
+printf "All necessary packages are installed.\n\n"
+
+
+echo # END OF DISPLAYING INSTALLATIONS REQUESTS TO PURSUE --------------------------
+
+
+# CREATING INSTALLATION PATHS -------------------------------------------------
+
+
+
+DIR=/usr/lib/.automatic_courses_player
+
+if [ -d "$DIR" ];then
+    echo "Directory $DIR exists"
+else
+    mkdir -p $DIR
+    echo "$DIR directory did not exist, and was created."
+fi
+
+cp -r * $DIR
+cd $DIR
+
+
+DIR=/usr/bin
+if [ -d "$DIR" ];then
+  echo "Bin directory exists."
+else
+  echo "Abort. Bin directory do not exist. Are you running a unix OS on your machine ? Check out /usr/bin directory existence."
+  exit 0
+fi
+
+mv ./pedt $DIR
+cd $DIR
 chmod +x ./pedt
+echo "Installation finished."
